//
// Created by ADMIN on 3/8/2024.
//

#ifndef PICO_MODBUS_VENTILATION_SPEED_PRESSURE_DATA_H
#define PICO_MODBUS_VENTILATION_SPEED_PRESSURE_DATA_H

float getSpeed(int pressure_);

#endif //PICO_MODBUS_VENTILATION_SPEED_PRESSURE_DATA_H
